[package]
name = "oddclient"
version = "0.1.0"
authors = ["Nemin32 <>"]

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winuser", "processthreadsapi", "memoryapi", "psapi"] }
bincode = "1.0.1"
serde = "1.0"
serde_derive = "1.0"